/**
 * Google Search Console report.
 *
 * Fetches GSC search analytics, sitemaps, and site list for cross-stitch.com,
 * then compares indexed pages against DynamoDB design metadata to produce an
 * indexed vs non-indexed design-page report.
 *
 * Configuration (env vars, all optional):
 *   GSC_SITE_URL        — verified site URL in GSC  (default: https://cross-stitch.com/)
 *   GSC_DAYS            — look-back window in days   (default: 90)
 *   GSC_INSPECT_LIMIT   — max URL inspections to run (default: 10)
 *   GSC_SAMPLE_SIZE     — random sitemap URLs to inspect for the indexed-rate
 *                         estimate below (default: 150)
 *   GSC_INSPECT_CONCURRENCY — parallel URL Inspection calls (default: 5)
 *   ITEMS_TABLE_NAME    — CrossStitchItems DDB table  (default: CrossStitchItems)
 *
 * Note on "indexed" counts: the Sitemaps API's `contents[].indexed` field
 * (see the gsc-sitemaps.json output) has been observed to always read 0 for
 * this property — it is not reliable and should not be used to track the
 * indexed/not-indexed split shown in the GSC UI's Page Indexing report. The
 * `sitemapIndexSample` section of the indexing report is a real substitute:
 * it draws a random sample of live sitemap.xml URLs and classifies each via
 * the URL Inspection API's `coverageState` (the same signal the UI report is
 * built from), giving a dated, comparable indexed% estimate with a margin of
 * error. Quota: URL Inspection is capped at 2,400 requests/day; the default
 * sample (150) plus the no-GSC-data inspection (10) stays well under that.
 * The API itself is slow (~6-7s/call observed) — calls run in small
 * concurrent batches (GSC_INSPECT_CONCURRENCY) so wall-clock time stays
 * bounded regardless of sample size; a naive sequential loop at this
 * per-call latency would blow past Lambda's 900s timeout at anything near
 * the old 300-sample default.
 * The sample result is also written to DynamoDB (CrossStitchBusinessHistory,
 * EntityType=GSC_INDEX_SAMPLE, SortKey=date) since local report files don't
 * survive between Lambda invocations — that DDB row is the durable trend.
 *
 * Design-pin-map (source of design URLs) is read live from DynamoDB
 * (CrossStitchBusinessHistory, EntityType=DESIGN_PIN_MAP, written by the
 * pinmap pipeline step) rather than a local reports/design-pin-map.json file
 * — that file is never regenerated by the current pinmap script and would
 * be stale/absent in Lambda's ephemeral /tmp anyway.
 *
 * Output files written to reports/gsc/:
 *   YYYY-MM-DD-gsc-sites.json
 *   YYYY-MM-DD-gsc-sitemaps.json
 *   YYYY-MM-DD-gsc-search-analytics.json
 *   YYYY-MM-DD-gsc-indexing-report.json   ← main comparison + sitemapIndexSample
 */

import fs from "fs";
import path from "path";
import dotenv from "dotenv";
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import { DynamoDBDocumentClient, QueryCommand } from "@aws-sdk/lib-dynamodb";
import {
  listSearchConsoleSites,
  getSearchAnalyticsByPage,
  inspectUrl,
  listSitemaps,
  type GscPage,
  type UrlInspectionResult,
} from "../src/services/searchConsole";
import { getAllDesignPinMap, putGscIndexSample } from "../src/services/historyStore";

dotenv.config({ path: path.join(process.cwd(), ".env") });

// ── Config ────────────────────────────────────────────────────────────────────

const SITE_URL = (process.env.GSC_SITE_URL ?? "https://cross-stitch.com/").replace(/\/?$/, "/");
const DAYS = Math.max(1, parseInt(process.env.GSC_DAYS ?? "90", 10));
const INSPECT_LIMIT = Math.max(0, parseInt(process.env.GSC_INSPECT_LIMIT ?? "10", 10));
const SAMPLE_SIZE = Math.max(0, parseInt(process.env.GSC_SAMPLE_SIZE ?? "150", 10));
const INSPECT_CONCURRENCY = Math.max(1, parseInt(process.env.GSC_INSPECT_CONCURRENCY ?? "5", 10));
const ITEMS_TABLE = process.env.ITEMS_TABLE_NAME ?? "CrossStitchItems";
const REGION = process.env.AWS_REGION ?? "us-east-1";

// coverageState values (from the URL Inspection API) that count as "indexed"
// in the GSC UI's Page Indexing report — everything else counts as not indexed.
const INDEXED_COVERAGE_STATES = new Set([
  "Submitted and indexed",
  "Indexed, not submitted in sitemap",
]);

// ── Types ─────────────────────────────────────────────────────────────────────

interface DesignEntry {
  designId: number;
  albumId: number;
  albumCaption: string;
  pinId: string;
  designCaption: string;
  designUrl: string;          // relative, e.g. /Cat-15-187-Free-Design.aspx
  nDownloaded: number;
}

interface IndexedDesign extends DesignEntry {
  fullUrl: string;
  gsc: Pick<GscPage, "clicks" | "impressions" | "ctr" | "position">;
}

interface UnindexedDesign extends DesignEntry {
  fullUrl: string;
  inspection?: UrlInspectionResult;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function dateStr(d: Date): string {
  return d.toISOString().slice(0, 10);
}

function daysAgo(n: number): string {
  const d = new Date();
  d.setUTCDate(d.getUTCDate() - n);
  return dateStr(d);
}

function yesterdayStr(): string {
  return daysAgo(1);
}

function ensureDir(p: string): void {
  if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true });
}

function save(filePath: string, data: unknown): void {
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + "\n");
  console.log(`  Saved → ${filePath}`);
}

/** Extract the URL path from a full URL for comparison with relative design URLs. */
function urlPath(fullUrl: string): string {
  try {
    return new URL(fullUrl).pathname;
  } catch {
    return fullUrl;
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function shuffle<T>(items: T[]): T[] {
  const copy = items.slice();
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

/** Fetch and parse the live sitemap.xml, returning every <loc> URL. */
async function fetchSitemapUrls(baseUrl: string): Promise<string[]> {
  const resp = await fetch(new URL("/sitemap.xml", baseUrl).toString());
  if (!resp.ok) {
    throw new Error(`GET /sitemap.xml → ${resp.status} ${resp.statusText}`);
  }
  const xml = await resp.text();
  const urls: string[] = [];
  const locRe = /<loc>([^<]+)<\/loc>/g;
  let match: RegExpExecArray | null;
  while ((match = locRe.exec(xml)) !== null) {
    urls.push(match[1]);
  }
  return urls;
}

// ── DynamoDB: fetch NDownloaded for each design ───────────────────────────────

async function fetchDownloadCounts(
  designIds: number[],
): Promise<Map<number, number>> {
  const counts = new Map<number, number>();
  if (designIds.length === 0) return counts;

  const ddb = DynamoDBDocumentClient.from(new DynamoDBClient({ region: REGION }), {
    marshallOptions: { removeUndefinedValues: true },
  });

  // Query Designs-index GSI (EntityType=DESIGN, range=NGlobalPage) — returns all
  // DESIGN rows. We project only DesignID + NDownloaded to keep it light.
  let exclusiveStartKey: Record<string, unknown> | undefined;
  const idSet = new Set(designIds);

  do {
    const resp = await ddb.send(
      new QueryCommand({
        TableName: ITEMS_TABLE,
        IndexName: "Designs-index",
        KeyConditionExpression: "EntityType = :et",
        ExpressionAttributeValues: { ":et": "DESIGN" },
        ProjectionExpression: "DesignID, NDownloaded",
        ExclusiveStartKey: exclusiveStartKey as Record<string, import("@aws-sdk/client-dynamodb").AttributeValue> | undefined,
      }),
    );

    for (const item of resp.Items ?? []) {
      const did = item["DesignID"] as number | undefined;
      if (did !== undefined && idSet.has(did)) {
        counts.set(did, (item["NDownloaded"] as number | undefined) ?? 0);
      }
    }

    exclusiveStartKey = resp.LastEvaluatedKey as Record<string, unknown> | undefined;
  } while (exclusiveStartKey);

  return counts;
}

// ── Main ──────────────────────────────────────────────────────────────────────

/** In Lambda, pass "/tmp" (or set REPORTS_DIR=/tmp) so output lands in writable ephemeral storage. */
export async function run(reportsDirOverride?: string): Promise<void> {
const endDate = yesterdayStr();
const startDate = daysAgo(DAYS + 1);
const reportDate = yesterdayStr();
const reportsDir = reportsDirOverride ?? process.env.REPORTS_DIR ?? path.join(process.cwd(), "reports");
const gscDir = path.join(reportsDir, "gsc");

console.log(`\nGSC report  site=${SITE_URL}  window=${startDate}→${endDate}  inspectLimit=${INSPECT_LIMIT}`);

ensureDir(gscDir);

// 1. Sites
console.log("\n[1/6] Listing GSC sites...");
const sites = await listSearchConsoleSites();
save(path.join(gscDir, `${reportDate}-gsc-sites.json`), sites);
console.log(`  ${sites.length} site(s) verified`);
sites.forEach((s) => console.log(`    ${s.permissionLevel.padEnd(20)} ${s.siteUrl}`));

if (sites.length === 0) {
  throw new Error("No verified GSC sites found for this account.");
}

// Prefer the site URL from the API (may be sc-domain: format) over the configured default.
// If GSC_SITE_URL is explicitly set, use it; otherwise pick the first owner-level site.
const activeSiteUrl =
  process.env.GSC_SITE_URL ??
  (sites.find((s) => s.permissionLevel === "siteOwner") ?? sites[0]).siteUrl;
console.log(`  Using site: ${activeSiteUrl}`);

// 2. Sitemaps
console.log("\n[2/6] Listing sitemaps...");
const sitemaps = await listSitemaps(activeSiteUrl);
save(path.join(gscDir, `${reportDate}-gsc-sitemaps.json`), sitemaps);
console.log(`  ${sitemaps.length} sitemap(s)`);
for (const sm of sitemaps) {
  const totals = sm.contents.map((c) => `${c.type}: ${c.indexed}/${c.submitted}`).join(", ");
  console.log(`    ${sm.path}  errors=${sm.errors}  ${totals}`);
}

// 3. Search analytics by page
console.log(`\n[3/6] Fetching search analytics (${startDate} → ${endDate})...`);
const gscPages = await getSearchAnalyticsByPage(activeSiteUrl, startDate, endDate);
save(path.join(gscDir, `${reportDate}-gsc-search-analytics.json`), gscPages);
console.log(`  ${gscPages.length} pages with GSC data`);

// Build path→GscPage lookup
const gscByPath = new Map<string, GscPage>();
for (const p of gscPages) {
  gscByPath.set(urlPath(p.page), p);
}

// 4. Load design-pin-map from DynamoDB (CrossStitchBusinessHistory, refreshed
// daily by the pinmap pipeline step — this is the live source of truth; the
// old local reports/design-pin-map.json file is never regenerated by the
// current pinmap script and should not be relied on).
console.log("\n[4/6] Loading design-pin-map from DynamoDB...");
let rawPinMap: Array<{
  designId: number;
  albumId: number;
  albumCaption: string;
  pinId: string;
  designCaption: string;
  designUrl: string;
}> = [];
try {
  rawPinMap = await getAllDesignPinMap();
  console.log(`  ${rawPinMap.length} designs in pin map`);
} catch (err) {
  console.warn(`  WARNING: design-pin-map fetch failed (${(err as Error).message}) — skipping design-level GSC comparison, sitemap sample below is unaffected`);
}

// 5. Enrich with NDownloaded from DDB
let downloadCounts = new Map<number, number>();
if (rawPinMap.length > 0) {
  console.log("\n[5/6] Fetching download counts from DynamoDB...");
  try {
    downloadCounts = await fetchDownloadCounts(rawPinMap.map((d) => d.designId));
    console.log(`  Got download counts for ${downloadCounts.size} design(s)`);
  } catch (err) {
    console.warn(`  WARNING: DDB download count fetch failed (${(err as Error).message}) — defaulting to 0`);
  }
}

const designs: DesignEntry[] = rawPinMap.map((d) => ({
  ...d,
  nDownloaded: downloadCounts.get(d.designId) ?? 0,
}));

// 6. Compare: indexed (has GSC data) vs no GSC data
const indexed: IndexedDesign[] = [];
const noGscData: UnindexedDesign[] = [];

for (const d of designs) {
  const fullUrl = SITE_URL.replace(/\/$/, "") + d.designUrl;
  const gscEntry = gscByPath.get(d.designUrl);

  if (gscEntry) {
    indexed.push({
      ...d,
      fullUrl,
      gsc: {
        clicks: gscEntry.clicks,
        impressions: gscEntry.impressions,
        ctr: gscEntry.ctr,
        position: gscEntry.position,
      },
    });
  } else {
    noGscData.push({ ...d, fullUrl });
  }
}

// Sort: indexed by impressions desc; no-GSC by nDownloaded desc
indexed.sort((a, b) => b.gsc.impressions - a.gsc.impressions);
noGscData.sort((a, b) => b.nDownloaded - a.nDownloaded);

// 7. URL inspection for top N designs with no GSC data
const inspected: UnindexedDesign[] = [];
if (INSPECT_LIMIT > 0 && noGscData.length > 0) {
  const toInspect = noGscData.slice(0, INSPECT_LIMIT);
  console.log(`\n  Running URL inspection for ${toInspect.length} design(s) with no GSC data...`);

  for (const d of toInspect) {
    try {
      const result = await inspectUrl(activeSiteUrl, d.fullUrl);
      inspected.push({ ...d, inspection: result });
      console.log(`    ${d.fullUrl}  verdict=${result.verdict}  coverage="${result.coverageState}"`);
    } catch (err) {
      inspected.push(d);
      console.warn(`    ${d.fullUrl}  inspection failed: ${(err as Error).message}`);
    }
  }
}

// Merge inspection results back into noGscData
const inspectedByUrl = new Map(inspected.map((d) => [d.fullUrl, d.inspection]));
const noGscDataWithInspection = noGscData.map((d) => ({
  ...d,
  inspection: inspectedByUrl.get(d.fullUrl),
}));

// Verdict summary from inspections
const verdictCounts: Record<string, number> = {};
for (const d of inspected) {
  if (d.inspection) {
    verdictCounts[d.inspection.verdict] = (verdictCounts[d.inspection.verdict] ?? 0) + 1;
  }
}

// 8. Sample the live sitemap for a real indexed-vs-not-indexed rate estimate.
// Unlike the Sitemaps API's `indexed` field (always 0 for this property — see
// header note), this classifies a random sample of actual sitemap URLs via
// the URL Inspection API, the same signal the GSC UI's Page Indexing report
// uses, so it's directly comparable across dated runs.
interface SitemapIndexSample {
  sitemapTotalUrls: number;
  sampleSize: number;
  indexedInSample: number;
  estimatedIndexedPercent: number;
  marginOfErrorPercent: number;
  coverageStateBreakdown: Record<string, number>;
}

let sitemapIndexSample: SitemapIndexSample | null = null;

if (SAMPLE_SIZE > 0) {
  console.log(`\n[6/6] Sampling ${SAMPLE_SIZE} live sitemap.xml URLs via URL Inspection...`);
  try {
    const allUrls = await fetchSitemapUrls(SITE_URL);
    const sample = shuffle(allUrls).slice(0, Math.min(SAMPLE_SIZE, allUrls.length));
    const coverageStateBreakdown: Record<string, number> = {};
    let indexedInSample = 0;

    // The URL Inspection API is slow (~6-7s/call observed) — sequential calls
    // would take ~35min for a 300-URL sample, blowing past Lambda's 900s cap.
    // Run in small concurrent batches instead; wall-clock is then driven by
    // parallelism, not sample size × per-call latency.
    for (let i = 0; i < sample.length; i += INSPECT_CONCURRENCY) {
      const batch = sample.slice(i, i + INSPECT_CONCURRENCY);
      await Promise.all(
        batch.map(async (url) => {
          try {
            const result = await inspectUrl(activeSiteUrl, url);
            coverageStateBreakdown[result.coverageState] = (coverageStateBreakdown[result.coverageState] ?? 0) + 1;
            if (INDEXED_COVERAGE_STATES.has(result.coverageState)) indexedInSample++;
          } catch (err) {
            coverageStateBreakdown["INSPECTION_FAILED"] = (coverageStateBreakdown["INSPECTION_FAILED"] ?? 0) + 1;
            console.warn(`    ${url}  inspection failed: ${(err as Error).message}`);
          }
        }),
      );
      await sleep(150); // brief pause between batches, not between individual calls
    }

    const p = sample.length > 0 ? indexedInSample / sample.length : 0;
    const marginOfErrorPercent = Math.round(1.96 * Math.sqrt((p * (1 - p)) / Math.max(1, sample.length)) * 1000) / 10;

    sitemapIndexSample = {
      sitemapTotalUrls: allUrls.length,
      sampleSize: sample.length,
      indexedInSample,
      estimatedIndexedPercent: Math.round(p * 1000) / 10,
      marginOfErrorPercent,
      coverageStateBreakdown,
    };

    console.log(
      `  ${indexedInSample}/${sample.length} sampled URLs indexed → ` +
      `${sitemapIndexSample.estimatedIndexedPercent}% ± ${marginOfErrorPercent}pp ` +
      `(of ${allUrls.length} total sitemap URLs)`
    );

    // Persist durably — /tmp (Lambda) or a local JSON file don't survive
    // between daily invocations, so this is the actual historical record.
    try {
      await putGscIndexSample({ date: reportDate, ...sitemapIndexSample });
      console.log(`  Saved → DDB CrossStitchBusinessHistory[GSC_INDEX_SAMPLE#${reportDate}]`);
    } catch (err) {
      console.warn(`  WARNING: failed to persist sitemapIndexSample to DDB (${(err as Error).message})`);
    }
  } catch (err) {
    console.warn(`  WARNING: sitemap sampling failed (${(err as Error).message})`);
  }
}

// 9. Write indexing report
const report = {
  generatedAt: new Date().toISOString(),
  dateRange: { startDate, endDate },
  siteUrl: activeSiteUrl,
  lookbackDays: DAYS,
  summary: {
    totalDesigns: designs.length,
    withGscData: indexed.length,
    withoutGscData: noGscData.length,
    gscCoveragePercent: designs.length > 0 ? Math.round((indexed.length / designs.length) * 100) : 0,
    inspected: inspected.length,
    inspectionVerdicts: verdictCounts,
    totalImpressions: indexed.reduce((s, d) => s + d.gsc.impressions, 0),
    totalClicks: indexed.reduce((s, d) => s + d.gsc.clicks, 0),
    totalDownloads: designs.reduce((s, d) => s + d.nDownloaded, 0),
  },
  sitemapIndexSample,
  designsWithGscData: indexed,
  designsWithoutGscData: noGscDataWithInspection,
};

const reportPath = path.join(gscDir, `${reportDate}-gsc-indexing-report.json`);
save(reportPath, report);

// Console summary
console.log(`
══ GSC Indexing Summary ═══════════════════════════════════════
  Total designs          : ${report.summary.totalDesigns}
  With GSC impressions   : ${report.summary.withGscData} (${report.summary.gscCoveragePercent}%)
  No GSC data            : ${report.summary.withoutGscData}
  URL inspections run    : ${report.summary.inspected}
  Inspection verdicts    : ${JSON.stringify(report.summary.inspectionVerdicts)}
  Total impressions (GSC): ${report.summary.totalImpressions.toLocaleString()}
  Total clicks (GSC)     : ${report.summary.totalClicks.toLocaleString()}
  Total downloads (DDB)  : ${report.summary.totalDownloads.toLocaleString()}
${sitemapIndexSample ? `  ── Sitemap indexed-rate estimate (real, dated) ──
  Sitemap URLs total     : ${sitemapIndexSample.sitemapTotalUrls}
  Sample size            : ${sitemapIndexSample.sampleSize}
  Indexed in sample      : ${sitemapIndexSample.indexedInSample}
  Estimated indexed %    : ${sitemapIndexSample.estimatedIndexedPercent}% ± ${sitemapIndexSample.marginOfErrorPercent}pp
  Coverage breakdown     : ${JSON.stringify(sitemapIndexSample.coverageStateBreakdown)}` : ""}
═══════════════════════════════════════════════════════════════
`);
}

async function main() {
  await run();
}

if (!process.env.AWS_LAMBDA_FUNCTION_NAME) {
  main().catch((err) => {
    console.error("Error:", err?.message || err);
    process.exit(1);
  });
}
