<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.7.400.1" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.400" />
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="log4net" Version="3.2.0" />
    <PackageReference Include="AWSSDK.SimpleEmail" Version="3.7.401.10" />
    <PackageReference Include="AWSSDK.EC2" version="3.7.413" />
    <PackageReference Include="AWSSDK.ElasticBeanstalk" Version="3.7.100" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\src\CrossStitch.Shared\CrossStitch.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="App.private.config" Condition="Exists('App.private.config')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Templates\*.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>