// DynamoDB wrapper for the CrossStitchBusinessHistory single-table store.
// Schema reference: plan/integration/business-history-schema.md §4.

import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import {
  DynamoDBDocumentClient,
  PutCommand,
  QueryCommand,
  BatchWriteCommand,
  type BatchWriteCommandOutput,
  UpdateCommand,
  GetCommand,
} from "@aws-sdk/lib-dynamodb";

const REGION = process.env.AWS_REGION || "us-east-1";
const TABLE = process.env.HISTORY_TABLE_NAME || "CrossStitchBusinessHistory";

const ddb = DynamoDBDocumentClient.from(new DynamoDBClient({ region: REGION }), {
  marshallOptions: { removeUndefinedValues: true },
});

export type EntityType =
  | "DAILY_BUSINESS"
  | "AI_ANALYSIS"
  | "DESIGN_PIN_MAP"
  | "DESIGN_PERFORMANCE"
  | "ANOMALY_EVENT"
  | "PROMOTED_AD_STATS"
  | "LANDING_PAGE_STATS"
  | "PIN_ATTRIBUTION"
  | "PINTEREST_TOKEN"
  | "BLOCKED_IP"
  | "WATCHED_IP";

export type AnalysisType = "trend" | "design";

export type AnomalyMetric =
  | "ctr"
  | "revenuePerHundredSessions"
  | "profit"
  | "ga4Sessions";

// Sort-key construction. Centralized so callers and queryRange agree.
function padDesignId(designId: number): string {
  return designId.toString().padStart(5, "0");
}

export const sortKey = {
  pinterestToken: () => "CURRENT" as const,
  dailyBusiness: (date: string) => date,
  aiAnalysis: (generatedAt: string, type: AnalysisType) =>
    `${generatedAt}#${type}`,
  designPinMap: (designId: number) => padDesignId(designId),
  designPerformance: (snapshotDate: string, designId: number) =>
    `${snapshotDate}#${padDesignId(designId)}`,
  anomalyEvent: (detectedAt: string, metric: AnomalyMetric) =>
    `${detectedAt}#${metric}`,
  promotedAdStats: (date: string, adId: string) => `${date}#${adId}`,
  landingPageStats: (date: string, page: string) => `${date}#${page}`,
  pinAttribution: (date: string, adId: string) => `${date}#${adId}`,
  blockedIp: (ip: string) => ip,
  watchedIp: (ip: string) => ip,
};

// Input shapes (callers pass domain fields; the store assembles the DDB item).
// writtenAt is generated by the put method.

export interface DailyBusinessInput {
  date: string;
  usdIlsRate?: number;
  spend: number;
  impressions: number;
  clicks: number;
  ctr: number;
  cpc: number;
  outboundClicks: number;
  ga4Sessions: number;
  ga4PaidSessions: number;
  ga4OrganicSessions: number;
  ga4ReferralSessions: number;
  adsenseRevenue: number;
  revenuePerHundredSessions?: number;
  profit: number;
}

export interface AiAnalysisInput {
  generatedAt: string;
  analysisType: AnalysisType;
  forDate: string;
  reasoning: string;
  markdownS3Key: string;
  // trend
  recommendedAction?: string;
  sourceHistoryRange?: { first: string; last: string };
  totalDaysAnalyzed?: number;
  // design
  topAlbums?: string[];
  underperformingAlbums?: string[];
  designDirectionsToCreate?: string[];
  totalDesignsAnalyzed?: number;
  // shared optional
  confidence?: number;
  sourceWindow?: { label: string; startDate: string; endDate: string };
}

export interface DesignPinMapInput {
  designId: number;
  albumId: number;
  albumCaption: string;
  pinId: string;
  designCaption: string;
  designUrl: string;
  pinLinkType?: string;
}

export interface DesignPerformanceInput {
  snapshotDate: string;
  windowLabel: string;
  windowStartDate: string;
  windowEndDate: string;
  designId: number;
  albumId: number;
  albumCaption: string;
  pinId: string;
  designCaption: string;
  designUrl: string;
  impressions: number;
  clicks: number;
  outboundClicks: number;
  ctr: number;
  saves: number;
  pinCreatedAt?: string;
  daysSinceCreation?: number;
  savesPerDay?: number;
  impressionsPerDay?: number;
  error?: string;
}

export interface AnomalyEventInput {
  detectedAt: string;
  forDate: string;
  metric: AnomalyMetric;
  observedValue: number;
  expectedMean: number;
  expectedSigma: number;
  deviationSigmas: number;
  direction: "above" | "below";
  notified?: boolean;
}

// Writes

export async function putDailyBusiness(input: DailyBusinessInput): Promise<void> {
  const { date, ...rest } = input;
  await ddb.send(
    new PutCommand({
      TableName: TABLE,
      Item: {
        EntityType: "DAILY_BUSINESS",
        SortKey: sortKey.dailyBusiness(date),
        ...rest,
        writtenAt: new Date().toISOString(),
      },
    })
  );
}

export async function putAiAnalysis(input: AiAnalysisInput): Promise<void> {
  const { generatedAt, analysisType, ...rest } = input;
  await ddb.send(
    new PutCommand({
      TableName: TABLE,
      Item: {
        EntityType: "AI_ANALYSIS",
        SortKey: sortKey.aiAnalysis(generatedAt, analysisType),
        analysisType,
        ...rest,
        writtenAt: new Date().toISOString(),
      },
    })
  );
}

export async function putDesignPinMap(input: DesignPinMapInput): Promise<void> {
  await ddb.send(
    new PutCommand({
      TableName: TABLE,
      Item: {
        EntityType: "DESIGN_PIN_MAP",
        SortKey: sortKey.designPinMap(input.designId),
        ...input,
        writtenAt: new Date().toISOString(),
      },
    })
  );
}

export async function putDesignPerformance(
  input: DesignPerformanceInput
): Promise<void> {
  await ddb.send(
    new PutCommand({
      TableName: TABLE,
      Item: {
        EntityType: "DESIGN_PERFORMANCE",
        SortKey: sortKey.designPerformance(input.snapshotDate, input.designId),
        ...input,
        writtenAt: new Date().toISOString(),
      },
    })
  );
}

export async function putAnomaly(input: AnomalyEventInput): Promise<void> {
  await ddb.send(
    new PutCommand({
      TableName: TABLE,
      Item: {
        EntityType: "ANOMALY_EVENT",
        SortKey: sortKey.anomalyEvent(input.detectedAt, input.metric),
        notified: false,
        ...input,
      },
    })
  );
}

// Mark an AI_ANALYSIS row as having had its recommendation-change alert sent.
export async function markAiAnalysisChangeNotified(sk: string): Promise<void> {
  await ddb.send(
    new UpdateCommand({
      TableName: TABLE,
      Key: { EntityType: "AI_ANALYSIS", SortKey: sk },
      UpdateExpression: "SET changeNotified = :t, changeNotifiedAt = :n",
      ExpressionAttributeValues: {
        ":t": true,
        ":n": new Date().toISOString(),
      },
    })
  );
}

// Mark a single ANOMALY_EVENT row as notified — called by the alerter after
// the email send succeeds. Stamps notifiedAt so the row carries its own audit
// trail without a separate journal.
export async function markAnomalyNotified(
  detectedAt: string,
  metric: AnomalyMetric
): Promise<void> {
  await ddb.send(
    new UpdateCommand({
      TableName: TABLE,
      Key: {
        EntityType: "ANOMALY_EVENT",
        SortKey: sortKey.anomalyEvent(detectedAt, metric),
      },
      UpdateExpression: "SET notified = :t, notifiedAt = :n",
      ExpressionAttributeValues: {
        ":t": true,
        ":n": new Date().toISOString(),
      },
    })
  );
}

// Batch writes (DDB caps BatchWriteItem at 25 items per call).

async function batchPutRows(items: Record<string, unknown>[]): Promise<void> {
  for (let i = 0; i < items.length; i += 25) {
    const chunk = items.slice(i, i + 25);
    let requestItems: Record<string, { PutRequest: { Item: Record<string, unknown> } }[]> | undefined = {
      [TABLE]: chunk.map((Item) => ({ PutRequest: { Item } })),
    };
    while (requestItems && Object.keys(requestItems).length > 0) {
      const res: BatchWriteCommandOutput = await ddb.send(
        new BatchWriteCommand({ RequestItems: requestItems }),
      );
      const unprocessed = res.UnprocessedItems;
      requestItems =
        unprocessed && Object.keys(unprocessed).length > 0
          ? (unprocessed as typeof requestItems)
          : undefined;
    }
  }
}

export async function batchPutDesignPinMap(
  inputs: DesignPinMapInput[]
): Promise<void> {
  const now = new Date().toISOString();
  await batchPutRows(
    inputs.map((input) => ({
      EntityType: "DESIGN_PIN_MAP",
      SortKey: sortKey.designPinMap(input.designId),
      ...input,
      writtenAt: now,
    }))
  );
}

export async function batchPutDesignPerformance(
  inputs: DesignPerformanceInput[]
): Promise<void> {
  const now = new Date().toISOString();
  await batchPutRows(
    inputs.map((input) => ({
      EntityType: "DESIGN_PERFORMANCE",
      SortKey: sortKey.designPerformance(input.snapshotDate, input.designId),
      ...input,
      writtenAt: now,
    }))
  );
}

export interface PromotedAdStatsInput {
  date: string;
  adId: string;
  destinationUrl: string;
  title: string;
  spend: number;
  impressions: number;
  clicks: number;
  outboundClicks: number;
  ctr: number;
}

export interface LandingPageStatsInput {
  date: string;
  page: string;           // path only, e.g. /Horse-16-70-Free-Design.aspx
  paidSessions: number;
  organicSessions: number;
  referralSessions: number;
}

export async function batchPutPromotedAdStats(inputs: PromotedAdStatsInput[]): Promise<void> {
  const now = new Date().toISOString();
  await batchPutRows(
    inputs.map((input) => ({
      EntityType: "PROMOTED_AD_STATS",
      SortKey: sortKey.promotedAdStats(input.date, input.adId),
      ...input,
      writtenAt: now,
    }))
  );
}

export async function batchPutLandingPageStats(inputs: LandingPageStatsInput[]): Promise<void> {
  const now = new Date().toISOString();
  await batchPutRows(
    inputs.map((input) => ({
      EntityType: "LANDING_PAGE_STATS",
      SortKey: sortKey.landingPageStats(input.date, input.page),
      ...input,
      writtenAt: now,
    }))
  );
}

export interface PinAttributionInput {
  date: string;
  adId: string;
  title: string;
  destinationUrl: string;
  clicks: number;
  outboundClicks: number;
  spend: number;
  paidSessions: number; // all sessions to pin's landing page (paid + organic + referral)
  attributedRevenue: number;
  profit: number;
}

export async function batchPutPinAttribution(inputs: PinAttributionInput[]): Promise<void> {
  const now = new Date().toISOString();
  await batchPutRows(
    inputs.map((input) => ({
      EntityType: "PIN_ATTRIBUTION",
      SortKey: sortKey.pinAttribution(input.date, input.adId),
      ...input,
      writtenAt: now,
    }))
  );
}

export interface BlockedIpInput {
  ip: string; // IPv4 address, no CIDR suffix (the /32 is added at WAF-sync time)
  reason: string;
  blockedAt?: string; // defaults to now
  ttlDays?: number; // defaults to 30; DDB expires the row after this, which
  // un-blocks the IP on the next WAF sync since it drops out of the query.
}

export interface BlockedIpRecord {
  EntityType: "BLOCKED_IP";
  SortKey: string; // the IP address
  ip: string;
  reason: string;
  blockedAt: string;
  ttl: number; // epoch seconds; DDB's native TTL attribute for this table
}

export async function putBlockedIp(input: BlockedIpInput): Promise<void> {
  const { ip, reason, blockedAt = new Date().toISOString(), ttlDays = 30 } = input;
  const ttl = Math.floor(Date.now() / 1000) + ttlDays * 86400;
  await ddb.send(
    new PutCommand({
      TableName: TABLE,
      Item: {
        EntityType: "BLOCKED_IP",
        SortKey: sortKey.blockedIp(ip),
        ip,
        reason,
        blockedAt,
        ttl,
      },
    })
  );
}

export interface WatchedIpInput {
  ip: string;
  reason: string;
  watchedAt?: string; // defaults to now
  ttlDays?: number; // defaults to 3; when this expires, the watch period is
  // over and a human should review the accumulated daily counts and decide
  // block/ignore. Does not block anything by itself.
}

export interface WatchedIpRecord {
  EntityType: "WATCHED_IP";
  SortKey: string; // the IP address
  ip: string;
  reason: string;
  watchedAt: string;
  ttl: number; // epoch seconds — when the watch period ends, not an auto-block
}

export async function putWatchedIp(input: WatchedIpInput): Promise<void> {
  const { ip, reason, watchedAt = new Date().toISOString(), ttlDays = 3 } = input;
  const ttl = Math.floor(Date.now() / 1000) + ttlDays * 86400;
  await ddb.send(
    new PutCommand({
      TableName: TABLE,
      Item: {
        EntityType: "WATCHED_IP",
        SortKey: sortKey.watchedIp(ip),
        ip,
        reason,
        watchedAt,
        ttl,
      },
    })
  );
}

export interface PinterestTokenRecord {
  access_token: string;
  refresh_token: string;
  expires_at_utc: string;
  scope: string;
  writtenAt: string;
  refreshedAt?: string;
}

export async function putPinterestToken(
  token: Omit<PinterestTokenRecord, "writtenAt">
): Promise<void> {
  await ddb.send(
    new PutCommand({
      TableName: TABLE,
      Item: {
        EntityType: "PINTEREST_TOKEN",
        SortKey: sortKey.pinterestToken(),
        ...token,
        writtenAt: new Date().toISOString(),
      },
    })
  );
}

export async function getPinterestToken(): Promise<PinterestTokenRecord | null> {
  const res = await ddb.send(
    new GetCommand({
      TableName: TABLE,
      Key: { EntityType: "PINTEREST_TOKEN", SortKey: sortKey.pinterestToken() },
    })
  );
  return res.Item ? (res.Item as PinterestTokenRecord) : null;
}

// Reads

export interface QueryRangeOpts {
  startKey?: string; // inclusive
  endKey?: string; // inclusive
  limit?: number;
  scanForward?: boolean; // default true (ascending)
}

export async function queryRange<T = Record<string, unknown>>(
  entityType: EntityType,
  opts: QueryRangeOpts = {}
): Promise<T[]> {
  const { startKey, endKey, limit, scanForward = true } = opts;

  const exprNames: Record<string, string> = { "#et": "EntityType" };
  const exprValues: Record<string, unknown> = { ":et": entityType };
  let keyExpr = "#et = :et";

  if (startKey !== undefined && endKey !== undefined) {
    keyExpr += " AND #sk BETWEEN :a AND :b";
    exprNames["#sk"] = "SortKey";
    exprValues[":a"] = startKey;
    exprValues[":b"] = endKey;
  } else if (startKey !== undefined) {
    keyExpr += " AND #sk >= :a";
    exprNames["#sk"] = "SortKey";
    exprValues[":a"] = startKey;
  } else if (endKey !== undefined) {
    keyExpr += " AND #sk <= :b";
    exprNames["#sk"] = "SortKey";
    exprValues[":b"] = endKey;
  }

  const items: T[] = [];
  let exclusiveStartKey: Record<string, unknown> | undefined;

  do {
    const res = await ddb.send(
      new QueryCommand({
        TableName: TABLE,
        KeyConditionExpression: keyExpr,
        ExpressionAttributeNames: exprNames,
        ExpressionAttributeValues: exprValues,
        ScanIndexForward: scanForward,
        ExclusiveStartKey: exclusiveStartKey,
        Limit: limit !== undefined ? limit - items.length : undefined,
      })
    );
    if (res.Items) items.push(...(res.Items as T[]));
    exclusiveStartKey = res.LastEvaluatedKey;
    if (limit !== undefined && items.length >= limit) break;
  } while (exclusiveStartKey);

  return limit !== undefined ? items.slice(0, limit) : items;
}
